name: test_conditions

on:
  workflow_dispatch:
    inputs:
      install_prerelease:
        description: 'Check this to install the prerelease version of medspacy if available and the version is newer than formal release.'  
        type: boolean   
        required: false
        default: false

jobs:

  test_win_linux_mac:
  
    # TODO: Do we care if this only runs on allowed branches since we check push/pull_request above?
    #if: github.ref == 'refs/heads/master' OR github.ref == 'refs/heads/develop'

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
        # python-version: [3.8, 3.9, "3.10.x", "3.11.x"]
        # revised from https://github.com/actions/cache/blob/main/examples.md#python---pip
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          - os: macos-latest
            path: ~/Library/Caches/pip
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Git clone repo and remove source code
      run: |
        pwd
        ls
        echo github.event.inputs.install_prerelease
        echo ${{ github.event.inputs.install_prerelease }} 
    
    - name: test_condition1
      if: ${{ github.event.inputs.install_prerelease }}
      run: |
        echo 'if: ${{ github.event.inputs.install_prerelease }}'


    - name: test_condition2
      if: ${{ github.event.inputs.install_prerelease }} == true
      run: |
        echo 'if: ${{ github.event.inputs.install_prerelease }} == true'  

    - name: test_condition3
      if: not ${{ github.event.inputs.install_prerelease }}
      run: |
        echo 'not ${{ github.event.inputs.install_prerelease }}'

    - name: test_condition4
      if: ${{ github.event.inputs.install_prerelease }} == false
      run: |
        echo 'if: ${{ github.event.inputs.install_prerelease }} == false'      
